//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiexpressEDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class InTaller
    {
        public int num_ingreso { get; set; }
        public string patente { get; set; }
        public string fabricante { get; set; }
        public int anno { get; set; }
        public string modelo { get; set; }
        public string servicio { get; set; }
        public string rut_cliente { get; set; }
    
        public virtual cliente cliente { get; set; }
    }
}
