//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDServiexpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoTaller
    {
        public int num_ingreso { get; set; }
        public string patente { get; set; }
        public int id_fabricante { get; set; }
        public int anno { get; set; }
        public string modelo { get; set; }
        public int id_servicio { get; set; }
        public string rut_cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Fabricante Fabricante { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
